apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: istio-system
data:
  alertmanager.yml: |
    global:
      resolve_timeout: 5m
    
    route:
      group_by: ['alertname', 'cluster']
      group_wait: 10s
      group_interval: 10s
      repeat_interval: 12h
      receiver: 'default'
      routes:
      - match:
          severity: critical
        receiver: 'critical'
      - match:
          severity: warning
        receiver: 'warning'
    
    receivers:
    - name: 'default'
      webhook_configs:
      - url: 'http://localhost:9093/webhook'
        send_resolved: true
    
    - name: 'critical'
      webhook_configs:
      - url: 'http://localhost:9093/webhook/critical'
        send_resolved: true
    
    - name: 'warning'
      webhook_configs:
      - url: 'http://localhost:9093/webhook/warning'
        send_resolved: true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-rules
  namespace: istio-system
data:
  istio-alerts.yml: |
    groups:
    - name: istio_mesh
      interval: 30s
      rules:
      
      # High error rate alert
      - alert: HighErrorRate
        expr: |
          (
            sum(rate(istio_requests_total{response_code=~"5.."}[5m]))
            /
            sum(rate(istio_requests_total[5m]))
          ) > 0.05
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "High error rate detected"
          description: "Error rate is {{ $value | humanizePercentage }} (threshold: 5%)"
      
      # Gateway down alert
      - alert: IngressGatewayDown
        expr: up{job="kubernetes-pods",app="istio-ingressgateway"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Ingress gateway is down"
          description: "Ingress gateway in {{ $labels.cluster }} is unavailable"
      
      # Istiod control plane down
      - alert: IstiodDown
        expr: up{job="kubernetes-pods",app="istiod"} == 0
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "Istio control plane is down"
          description: "Istiod in {{ $labels.cluster }} is unavailable"
      
      # High latency alert
      - alert: HighLatency
        expr: |
          histogram_quantile(0.99,
            sum(rate(istio_request_duration_milliseconds_bucket[5m])) by (le, destination_service)
          ) > 1000
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High latency detected"
          description: "P99 latency for {{ $labels.destination_service }} is {{ $value }}ms"
      
      # Cross-cluster connectivity issue
      - alert: CrossClusterConnectivityIssue
        expr: |
          sum(rate(istio_requests_total{source_cluster!="destination_cluster"}[5m])) == 0
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "No cross-cluster traffic detected"
          description: "Cross-cluster service mesh communication may be broken"
      
      # Circuit breaker triggered
      - alert: CircuitBreakerTriggered
        expr: |
          sum(rate(istio_requests_total{response_flags=~".*UO.*"}[5m])) > 0
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "Circuit breaker has been triggered"
          description: "Circuit breaker triggered for {{ $labels.destination_service }}"
      
      # High connection pool usage
      - alert: HighConnectionPoolUsage
        expr: |
          (
            envoy_cluster_upstream_cx_active
            /
            envoy_cluster_circuit_breakers_default_cx_pool_open
          ) > 0.8
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High connection pool usage"
          description: "Connection pool usage is {{ $value | humanizePercentage }} for {{ $labels.cluster_name }}"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertmanager
  namespace: istio-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alertmanager
  template:
    metadata:
      labels:
        app: alertmanager
    spec:
      containers:
      - name: alertmanager
        image: docker.io/prom/alertmanager:v0.26.0
        args:
          - '--config.file=/etc/alertmanager/alertmanager.yml'
          - '--storage.path=/alertmanager'
        ports:
        - containerPort: 9093
          name: http
        volumeMounts:
        - name: config
          mountPath: /etc/alertmanager
        - name: storage
          mountPath: /alertmanager
      volumes:
      - name: config
        configMap:
          name: alertmanager-config
      - name: storage
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: alertmanager
  namespace: istio-system
spec:
  selector:
    app: alertmanager
  ports:
  - port: 9093
    targetPort: 9093
    name: http
